on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: debug
        run: ls -R
      - name: Testing the plugin
        id: test
        uses: webtech-network/test-plugin@v5
        with:
          html-weight: 50
          css-weight: 20
          js-weight: 30
          timeout: 40
      - name: autograder
        id: autograde
        uses: webtech-network/webcode-autograder@test
        with:
          html-weight: 50
          css-weight: 20
          js-weight: 30
          timeout: 40
